# Generated by Django 5.0.7 on 2024-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Critico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('email', models.EmailField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=250)),
                ('video', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
